main = ".open-next/worker.js"
name = "radii-web"
compatibility_date = "2025-03-25"
compatibility_flags = ["nodejs_compat"]

[build.upload]
format = "service-worker"

[assets]
directory = ".open-next/assets"
binding = "ASSETS"